// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal status for a job recorded in the `job_history` table.
 */
export type JobHistoryStatus = "Succeeded" | "Retried" | "DeadLettered";
