// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The input type used to render a setting in admin forms.
 *
 * Each variant maps to a specific form widget. The `parameters` field
 * on [`Setting`] provides additional constraints and options for the widget.
 */
export type SettingType = "Text" | "Textarea" | "Number" | "Boolean" | "Select" | "Multiselect" | "Email" | "Url" | "Color" | "Date" | "Datetime" | "File" | "Image" | "Json" | "Password" | "Code";
